### ISSUE TITLE
Bug: User getting directed to the wrong location  

### ISSUE THREAD

**Issue by thisiskaransgit** [moja-global/Handbook#22]
**Steps to Reproduce**
1. Go to https://moja-global.github.io/Handbook/Chapter5/section_two_a.html#installing-python
2. Click on `Existing Python Installation`

You will be redirected to another site 

**Solution** 
- Remove the link from the `Existing Python Installation`
- Or redirect the user to the right section which is given on the same page 

**Also**:
 Add space between `New Python installation` and the previous line.
 
![Screenshot from 2023-01-31 23-35-09](https://user-images.githubusercontent.com/92504666/215845691-68d9caf9-dfe1-4b11-9128-bfa4f1b501c7.png)

**Comment by octonawish-akcodes** [comment]
I have raised a PR that will fix this issue #24
